apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://github.com/blairdrummond/terragrunt-experiment-manifests.git'
  - 'https://kubernetes.github.io/ingress-nginx'
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to my-project
    policies:
    - p, proj:platform:read-only, applications, get, platform/*, allow
    groups:
    - platform
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - list:
      elements:
      # - app: cert-manager
      - app: nginx
      - app: shipwright-build
      - app: argo
      - app: argo-events
      - app: default
  template:
    metadata:
      name: 'platform-{{app}}'
      namespace: argocd
    spec:
      project: platform
      source:
        repoURL: https://github.com/blairdrummond/terragrunt-experiment-manifests.git
        targetRevision: HEAD
        path: applications/platform/{{app}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
