apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: web-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'web-system'
    server: '*'
  - namespace: 'shipwright-build'
    server: '*'
  sourceRepos:
  - 'https://github.com/blairdrummond/terragrunt-experiment-manifests.git'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - list:
      elements:
      - app: liatrio-demo
  template:
    metadata:
      name: 'web-system-{{app}}'
      namespace: argocd
    spec:
      project: web-system
      source:
        repoURL: https://github.com/blairdrummond/terragrunt-experiment-manifests.git
        targetRevision: HEAD
        path: applications/web-system/{{app}}
      destination:
        server: https://kubernetes.default.svc
        namespace: web-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
