apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tekton.yaml
- shipwright.yaml
# strategies
- https://raw.githubusercontent.com/shipwright-io/build/main/samples/buildstrategy/kaniko/buildstrategy_kaniko-trivy_cr.yaml

# We're doing this in terraform
patchesStrategicMerge:
- |-
  apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    name: tekton-pipelines-webhook
    namespace: tekton-pipelines
  $patch: delete
