apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml


patchesJson6902:
- target:
    kind: ClusterRole
    name: argo-cluster-role
  patch: |-
    - op: add
      path: /rules/0/resources/-
      value: pods/log
- target:
    kind: Deployment
    name: argo-server
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - server
      - --secure=false
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe/httpGet/scheme
      value: HTTP



# We're doing this in terraform
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: workflow-controller-configmap
  $patch: delete
