apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-system

resources:
- deployment.yaml
- service.yaml
# Auto refresh images
- refresh-imago.yaml
- refresh-imago-rbac.yaml
# Ingress
- ingress.yaml
