apiVersion: v1
kind: ServiceAccount
metadata:
  name: imago
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: imago
rules:
  - apiGroups:
      - ""
      - apps
    resources:
    - pods
    - replicasets
    - statefulsets
    verbs:
    - list
  - apiGroups:
      - ""
      - batch
    resources:
    - cronjobs
    verbs:
    - get
    - list
    - update
  - apiGroups:
      - ""
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imago
roleRef:
  kind: Role
  name: imago
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: imago
