apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: imago
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-app: imago
        spec:
          restartPolicy: Never
          serviceAccount: imago
          serviceAccountName: imago
          containers:
            - name: imago
              image: philpep/imago
              imagePullPolicy: Always
              args: ["-restart"]
