apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: "liatrio-demo-"

resources:
- build.yaml
- buildrun-2022-03-30.yaml
#- buildrun-2022-02-17.yaml

patches:
  - patch: |-
      apiVersion: shipwright.io/v1alpha1
      kind: BuildRun
      metadata:
        name: not-used
      spec:
        buildRef:
          name: liatrio-demo-build
        serviceAccount:
          generate: true
        output:
          credentials:
            name: registry-write
    target:
      group: shipwright.io
      kind: BuildRun
