apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.15
    chart: ingress-nginx
    helm:
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/do-loadbalancer-name: liatrio-demo
              service.beta.kubernetes.io/do-loadbalancer-hostname: workaround.happylittlecloud.xyz
              service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "false"
              service.beta.kubernetes.io/do-loadbalancer-http-ports: "80"
              service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
              service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
